version: '3.7'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: kratos
      MYSQL_PASSWORD: supersecret
      MYSQL_DATABASE: kratos
      MYSQL_ROOT_PASSWORD: supersecret
    command:
      - --sql-mode=TRADITIONAL
    volumes:
      - mysqldbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=supersecret"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - intranet
  
  jackson:
    image: boxyhq/jackson:latest
    restart: always
    environment:
      - DB_ENGINE=sql
      - DB_TYPE=mysql
      - DB_URL=mysql://kratos:supersecret@db:3306/kratos
      - EXTERNAL_URL=${EXTERNAL_URL}
      - JACKSON_API_KEYS=secret-api-key-change-me
      - NEXTAUTH_URL=${EXTERNAL_URL}
      - NEXTAUTH_SECRET=super-secret-nextauth-secret
      - NEXTAUTH_ADMIN_CREDENTIALS=admin@example.com:password123
      - NODE_ENV=development
      - OPENID_RSA_PRIVATE_KEY=${OPENID_PRIVATE_KEY}
      - OPENID_RSA_PUBLIC_KEY=${OPENID_PUBLIC_KEY}
      - SMTP_HOST=mailslurper
      - SMTP_PORT=1025
    ports:
      - "5225:5225"
    networks:
      - intranet
    depends_on:
      db:
        condition: service_healthy

  kratos-migrate:
    image: oryd/kratos:v25.4.0
    environment:
      DSN: mysql://kratos:supersecret@tcp(db:3306)/kratos?parseTime=true
    volumes:
      - type: bind
        source: .
        target: /etc/config/kratos
    command:
      - migrate
      - sql
      - mysql://kratos:supersecret@tcp(db:3306)/kratos?parseTime=true
      - --yes
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v25.4.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
    networks:
      - intranet
    restart: on-failure

  kratos:
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
      jackson:
        condition: service_started
    image: oryd/kratos:v25.4.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=mysql://kratos:supersecret@tcp(db:3306)/kratos?parseTime=true  
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID=${GOOGLE_CLIENT_ID}  
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_1_CLIENT_ID=${APPLE_CLIENT_ID}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_1_APPLE_PRIVATE_KEY_ID=${APPLE_PRIVATE_KEY_ID}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_1_APPLE_PRIVATE_KEY=${APPLE_PRIVATE_KEY}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_1_APPLE_TEAM_ID=${APPLE_TEAM_ID}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_2_MICROSOFT_TENANT=${MICROSOFT_TENANT_ID}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_ID=jackson
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_PROVIDER=generic
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_CLIENT_ID=${JACKSON_CLIENT_ID}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_CLIENT_SECRET=${JACKSON_CLIENT_SECRET}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_ISSUER_URL=${EXTERNAL_URL}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_3_MAPPER_URL=file:///etc/config/kratos/mappers/oidc.jackson.jsonnet
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

networks:
  intranet:
volumes:
  mysqldbdata:
