version: '3.7'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: kratos
      MYSQL_PASSWORD: supersecret
      MYSQL_DATABASE: kratos
      MYSQL_ROOT_PASSWORD: supersecret
    command:
      - --sql-mode=TRADITIONAL
    volumes:
      - mysqldbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=supersecret"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - intranet

  kratos-migrate:
    image: oryd/kratos:v25.4.0
    environment:
      DSN: mysql://kratos:supersecret@tcp(db:3306)/kratos?parseTime=true
    volumes:
      - type: bind
        source: .
        target: /etc/config/kratos
    command:
      - migrate
      - sql
      - mysql://kratos:supersecret@tcp(db:3306)/kratos?parseTime=true
      - --yes
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v25.4.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
    networks:
      - intranet
    restart: on-failure

  kratos:
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
    image: oryd/kratos:v25.4.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      DSN: mysql://kratos:supersecret@tcp(db:3306)/kratos?parseTime=true
    volumes:
      - type: bind
        source: .
        target: /etc/config/kratos
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

networks:
  intranet:
volumes:
  mysqldbdata:
